### ISSUE TITLE
ugen_xxx stragglers

### ISSUE THREAD

**Issue by spencersalazar** [spencersalazar/ckdoc#2]

**Comment by ericheep** [comment]
Almost complete, would like some more info on a few under utilized and undocumented functions.

For LiSa:
pan, voicePan, getVoice, value (as opposed to valueAt)

For DelayP:
window

**Comment by spencersalazar** [comment]
Looks like `pan`/`voicePan` are the same, where `pan(int i,float p)` sets the pan for the voice `i`, `pan(float p)` sets the pan for voice 0, `pan(int i)` retrieves the pan for voice `i`, and `pan()` returns the pan for voice 0. 

`value` appears to get retrieve the sample value at the given position in a voice or voice 0, depending on if the optional int parameter is supplied. In contrast with `valueAt`, `value` seems to work with specific voices whereas `valueAt` works with the underlying buffer. Not sure practically how this works out, except maybe if the voices have different offsets/ramps/durations/etc. 

`getVoice` returns an "available" voice to use or `-1` if no voice is available. An available voice is basically one that isn't currently playing something. 

Probably okay to leave `DelayP.window` undocumented, `DelayP` seems to be one of those bespoke ChucK hacker ugens.

**Comment by ericheep** [comment]
Cool, followed your notes.
